import json
upload_json = {
    "upload bias": True,
    "bias model encid": "ENCSR868FGK",
    "experiment": "ENCSR868FGK",
    "bam files": [
        "ENCFF077FBI", "ENCFF128WZG", "ENCFF534DCE"
    ],
    "assay": "ATAC-seq",
    "observed signal profile bigWig": "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/data/K562_unstranded.bw",
    "models tar": {
        "file.paths": [
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/READMES/models.README",
                "README.md"
            ]
        ],
        "logs.models.ENCSR868FGK": {
            "file.paths": null
        },
        "fold_0": {
            "file.paths": [
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/chrombpnet_wo_bias.h5",
                    "model.chrombpnet_nobias.fold_0.ENCSR868FGK.h5"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/chrombpnet.h5",
                    "model.chrombpnet.fold_0.ENCSR868FGK.h5"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/bias_model_scaled.h5",
                    "model.bias_scaled.fold_0.ENCSR868FGK.h5"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/new_model_formats/chrombpnet_wo_bias.tar",
                    "model.chrombpnet_nobias.fold_0.ENCSR868FGK.tar"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/new_model_formats/chrombpnet.tar",
                    "model.chrombpnet.fold_0.ENCSR868FGK.tar"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/new_model_formats/bias_model_scaled.tar",
                    "model.bias_scaled.fold_0.ENCSR868FGK.tar"
                ]
            ],
            "logs.models.fold_0.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_chrombpnet_model.log",
                        "logfile_v1.modelling.fold_0.ENCSR868FGK.stdout.txt"
                    ],
                ]
            }
        },
        "fold_1": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/chrombpnet_wo_bias.h5",
                    "model.chrombpnet_nobias.fold_1.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/chrombpnet.h5",
                    "model.chrombpnet.fold_1.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/bias_model_scaled.h5",
                    "model.bias_scaled.fold_1.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/new_model_formats/chrombpnet_wo_bias.tar",
                    "model.chrombpnet_nobias.fold_1.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/new_model_formats/chrombpnet.tar",
                    "model.chrombpnet.fold_1.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/new_model_formats/bias_model_scaled.tar",
                    "model.bias_scaled.fold_1.ENCSR868FGK.tar"
                ]
            ],
            "logs.models.fold_1.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_chrombpnet_model.log",
                        "logfile_v1.modelling.fold_1.ENCSR868FGK.stdout.txt"
                    ],
                ]
            }
        },
        "fold_2": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/chrombpnet_wo_bias.h5",
                    "model.chrombpnet_nobias.fold_2.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/chrombpnet.h5",
                    "model.chrombpnet.fold_2.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/bias_model_scaled.h5",
                    "model.bias_scaled.fold_2.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/new_model_formats/chrombpnet_wo_bias.tar",
                    "model.chrombpnet_nobias.fold_2.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/new_model_formats/chrombpnet.tar",
                    "model.chrombpnet.fold_2.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/new_model_formats/bias_model_scaled.tar",
                    "model.bias_scaled.fold_2.ENCSR868FGK.tar"
                ]
            ],
            "logs.models.fold_2.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_chrombpnet_model.log",
                        "logfile_v1.modelling.fold_2.ENCSR868FGK.stdout.txt"
                    ],
                ]
            }
        },
        "fold_3": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/chrombpnet_wo_bias.h5",
                    "model.chrombpnet_nobias.fold_3.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/chrombpnet.h5",
                    "model.chrombpnet.fold_3.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/bias_model_scaled.h5",
                    "model.bias_scaled.fold_3.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/new_model_formats/chrombpnet_wo_bias.tar",
                    "model.chrombpnet_nobias.fold_3.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/new_model_formats/chrombpnet.tar",
                    "model.chrombpnet.fold_3.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/new_model_formats/bias_model_scaled.tar",
                    "model.bias_scaled.fold_3.ENCSR868FGK.tar"
                ]
            ],
            "logs.models.fold_3.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_chrombpnet_model.log",
                        "logfile_v1.modelling.fold_3.ENCSR868FGK.stdout.txt"
                    ],
                ]
            }
        },
        "fold_4": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/chrombpnet_wo_bias.h5",
                    "model.chrombpnet_nobias.fold_4.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/chrombpnet.h5",
                    "model.chrombpnet.fold_4.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/bias_model_scaled.h5",
                    "model.bias_scaled.fold_4.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/new_model_formats/chrombpnet_wo_bias.tar",
                    "model.chrombpnet_nobias.fold_4.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/new_model_formats/chrombpnet.tar",
                    "model.chrombpnet.fold_4.ENCSR868FGK.tar"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/new_model_formats/bias_model_scaled.tar",
                    "model.bias_scaled.fold_4.ENCSR868FGK.tar"
                ]
            ],
            "logs.models.fold_4.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_chrombpnet_model.log",
                        "logfile_v1.modelling.fold_4.ENCSR868FGK.stdout.txt"
                    ],
                ]
            }
        }
    },
    "training and test regions tar": {
        "file.paths": [
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/READMES/training_test_regions.README",
                "README.md"
            ],
            [
                "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/data/peaks_no_blacklist.bed.gz",
                "peaks.all_input_regions.ENCSR868FGK.bed.gz"
            ]
        ],
        "logs.training_test_regions.ENCSR868FGK": {
            "file.paths": [
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/data/K562_preprocessing.log",
                    "logfile_v1.preprocessing.ENCSR868FGK.stdout.txt"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chrombpnet/model_inputs/ENCODE_ATAC_downloads/K562/script.sh",
                    "logfile_v2.preprocessing.ENCSR868FGK.stdout.txt"
                ]
            ]
        },
        "fold_0": {
            "file.paths": [
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/negatives_data/negatives_with_summit.bed.gz",
                    "nonpeaks.all_input_regions.fold_0.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/splits_format//fold_0.json",
                    "cv_params.fold_0.json"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_test_regions/peaks.trainingset.bed.gz",
                    "peaks.trainingset.fold_0.ENCSR868FGK.bed.gz"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_test_regions/peaks.validationset.bed.gz",
                    "peaks.validationset.fold_0.ENCSR868FGK.bed.gz"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_test_regions/peaks.testset.bed.gz",
                    "peaks.testset.fold_0.ENCSR868FGK.bed.gz"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_test_regions/nonpeaks.trainingset.bed.gz",
                    "nonpeaks.trainingset.fold_0.ENCSR868FGK.bed.gz"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_test_regions/nonpeaks.validationset.bed.gz",
                    "nonpeaks.validationset.fold_0.ENCSR868FGK.bed.gz"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/train_test_regions/nonpeaks.testset.bed.gz",
                    "nonpeaks.testset.fold_0.ENCSR868FGK.bed.gz"
                ]
            ],
            "logs.training_test_regions.fold_0.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/fold_0.ENCSR868FGK_test.log",
                        "logfile.gc_matching.fold_0.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/test.fold_0.negatives_compared_with_foreground.png",
                        "logfile.gc_matching.fold_0.ENCSR868FGK.stdout.png"
                    ]
                ]
            }
        },
        "fold_1": {
            "file.paths": [
                 [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/negatives_data_1/negatives_with_summit.bed.gz",
                    "nonpeaks.all_input_regions.fold_1.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/splits_format//fold_1.json",
                    "cv_params.fold_1.json"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/peaks.trainingset.bed.gz",
                    "peaks.trainingset.fold_1.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/peaks.validationset.bed.gz",
                    "peaks.validationset.fold_1.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/peaks.testset.bed.gz",
                    "peaks.testset.fold_1.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/nonpeaks.trainingset.bed.gz",
                    "nonpeaks.trainingset.fold_1.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/nonpeaks.validationset.bed.gz",
                    "nonpeaks.validationset.fold_1.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/nonpeaks.testset.bed.gz",
                    "nonpeaks.testset.fold_1.ENCSR868FGK.bed.gz"
                ]
            ],
            "logs.training_test_regions.fold_1.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/fold_1.ENCSR868FGK_test.log",
                        "logfile.gc_matching.fold_1.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/test.fold_1.negatives_compared_with_foreground.png",
                        "logfile.gc_matching.fold_1.ENCSR868FGK.stdout.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/pconv.log.o",
                        "logfile.regions.formatting.fold_1.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/train_test_regions/pconv.log.e",
                        "logfile.regions.formatting.fold_1.ENCSR868FGK.stderr.txt"
                    ]
                ]
            }
        },
        "fold_2": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/splits_format//fold_2.json",
                    "cv_params.fold_2.json"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/peaks.trainingset.bed.gz",
                    "peaks.trainingset.fold_2.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/peaks.validationset.bed.gz",
                    "peaks.validationset.fold_2.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/peaks.testset.bed.gz",
                    "peaks.testset.fold_2.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/nonpeaks.trainingset.bed.gz",
                    "nonpeaks.trainingset.fold_2.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/nonpeaks.validationset.bed.gz",
                    "nonpeaks.validationset.fold_2.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/nonpeaks.testset.bed.gz",
                    "nonpeaks.testset.fold_2.ENCSR868FGK.bed.gz"
                ]
            ],
            "logs.training_test_regions.fold_2.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/fold_2.ENCSR868FGK_test.log",
                        "logfile.gc_matching.fold_2.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/test.fold_2.negatives_compared_with_foreground.png",
                        "logfile.gc_matching.fold_2.ENCSR868FGK.stdout.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/pconv.log.o",
                        "logfile.regions.formatting.fold_2.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/train_test_regions/pconv.log.e",
                        "logfile.regions.formatting.fold_2.ENCSR868FGK.stderr.txt"
                    ]
                ]
            }
        },
        "fold_3": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/splits_format//fold_3.json",
                    "cv_params.fold_3.json"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/peaks.trainingset.bed.gz",
                    "peaks.trainingset.fold_3.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/peaks.validationset.bed.gz",
                    "peaks.validationset.fold_3.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/peaks.testset.bed.gz",
                    "peaks.testset.fold_3.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/nonpeaks.trainingset.bed.gz",
                    "nonpeaks.trainingset.fold_3.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/nonpeaks.validationset.bed.gz",
                    "nonpeaks.validationset.fold_3.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/nonpeaks.testset.bed.gz",
                    "nonpeaks.testset.fold_3.ENCSR868FGK.bed.gz"
                ]
            ],
            "logs.training_test_regions.fold_3.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/fold_3.ENCSR868FGK_test.log",
                        "logfile.gc_matching.fold_3.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/test.fold_3.negatives_compared_with_foreground.png",
                        "logfile.gc_matching.fold_3.ENCSR868FGK.stdout.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/pconv.log.o",
                        "logfile.regions.formatting.fold_3.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/train_test_regions/pconv.log.e",
                        "logfile.regions.formatting.fold_3.ENCSR868FGK.stderr.txt"
                    ]
                ]
            }
        },
        "fold_4": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/splits_format//fold_4.json",
                    "cv_params.fold_4.json"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/peaks.trainingset.bed.gz",
                    "peaks.trainingset.fold_4.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/peaks.validationset.bed.gz",
                    "peaks.validationset.fold_4.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/peaks.testset.bed.gz",
                    "peaks.testset.fold_4.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/nonpeaks.trainingset.bed.gz",
                    "nonpeaks.trainingset.fold_4.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/nonpeaks.validationset.bed.gz",
                    "nonpeaks.validationset.fold_4.ENCSR868FGK.bed.gz"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/nonpeaks.testset.bed.gz",
                    "nonpeaks.testset.fold_4.ENCSR868FGK.bed.gz"
                ]
            ],
            "logs.training_test_regions.fold_4.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/fold_4.ENCSR868FGK_test.log",
                        "logfile.gc_matching.fold_4.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/test/test.fold_4.negatives_compared_with_foreground.png",
                        "logfile.gc_matching.fold_4.ENCSR868FGK.stdout.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/pconv.log.o",
                        "logfile.regions.formatting.fold_4.ENCSR868FGK.stdout.txt"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/train_test_regions/pconv.log.e",
                        "logfile.regions.formatting.fold_4.ENCSR868FGK.stderr.txt"
                    ]
                ]
            }
        }
    },
    "model performance metrics tar": {
        "file.paths": [
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/READMES/performance_metrics.README",
                "README.md"
            ],
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/preprocessing/bigWigs/ENCSR868FGK.png",
                "bias_motif.shift_qc.obs_signal_profile.ENCSR868FGK.png"
            ],
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/preprocessing/sorted_bams/sorted_ENCSR868FGK.samstats.qc",
                "samstats.obs_signal_profile.ENCSR868FGK.txt"
            ],
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/median_chrombpnet_performance.json",
                "performance_metrics.chrombpnet.fold_median.ENCSR868FGK.json"
            ],
            [
                "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/median_chrombpnet_nobias_performance.json",
                "performance_metrics.chrombpnet_nobias.fold_median.ENCSR868FGK.json"
            ]
        ],
        "logs.performance_metrics.ENCSR868FGK": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/preprocessing/samstats.log.e",
                    "logfile.samstats.ENCSR868FGK.stderr.txt"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/preprocessing/samstats.log.o",
                    "logfile.samstats.ENCSR868FGK.stdout.txt"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/preprocessing/bigWigs/ENCSR868FGK.png.score.txt",
                    "logfile.obs_signal.qc.ENCSR868FGK.stdout.txt"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/negatives_data/negatives_compared_with_foreground.png",
                    "logfile.gc_matching.qc.ENCSR868FGK.stdout.png"
                ]
            ]
        },
        "fold_0": {
            "file.paths": [
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_predictions.h5",
                    "predictions.chrombpnet.testset.fold_0.ENCSR868FGK.h5"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_wo_bias_predictions.h5",
                    "predictions.chrombpnet_nobias.testset.fold_0.ENCSR868FGK.h5"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.peaks.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_wo_bias_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.peaks.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.all.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_wo_bias_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.all.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.peaks.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_wo_bias_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.peaks.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.all.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_wo_bias_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.all.testset.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_metrics.json",
                    "performance_metrics.chrombpnet.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/chrombpnet_wo_bias_metrics.json",
                    "performance_metrics.chrombpnet_nobias.fold_0.ENCSR868FGK.png"
                ],
                [
                    "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected_footprints_score.txt",
                    "footprint_plot.chrombpnet_nobias.bias_motif.summary.fold_0.ENCSR868FGK.png"
                ]
            ],
            "logs.performance_metrics.fold_0.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/preds.log.e",
                        "preds.log.e"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/test/preds.log.o",
                        "preds.log.o"
                    ]
                ]
            },
            "footprint_plot.bias_motif.fold_0.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected.tn5_1.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_1.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias.tn5_1.footprint.png",
                        "footprint.bias_scaled.bias_motif_1.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected.tn5_2.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_2.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias.tn5_2.footprint.png",
                        "footprint.bias_scaled.bias_motif_2.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected.tn5_3.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_3.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias.tn5_3.footprint.png",
                        "footprint.bias_scaled.bias_motif_3.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected.tn5_4.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_4.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias.tn5_4.footprint.png",
                        "footprint.bias_scaled.bias_motif_4.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected.tn5_5.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_5.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias.tn5_5.footprint.png",
                        "footprint.bias_scaled.bias_motif_5.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias_footprints_score.txt",
                        "footprint_plot.bias_scaled.bias_motif.summary.fold_0.ENCSR868FGK.png"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/bias_footprints.h5",
                        "footprint.bias_scaled.bias_motif.all.fold_0.ENCSR868FGK.h5"
                    ],
                    [
                        "/mnt/lab_data2/anusri/chrombpnet/results/chrombpnet/ATAC_PE/K562/nautilus_runs/K562_02.17.2022_bias_128_4_1234_0.5_fold_0/chrombpnet_model/footprints/corrected_footprints.h5",
                        "footprint.chrombpnet_nobias.bias_motif.all.fold_0.ENCSR868FGK.h5"
                    ]
                ]
            }
        },
        "fold_1": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_predictions.h5",
                    "predictions.chrombpnet.testset.fold_1.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_wo_bias_predictions.h5",
                    "predictions.chrombpnet_nobias.testset.fold_1.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.peaks.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.peaks.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.all.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.all.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.peaks.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.peaks.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.all.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.all.testset.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_metrics.json",
                    "performance_metrics.chrombpnet.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/chrombpnet_wo_bias_metrics.json",
                    "performance_metrics.chrombpnet_nobias.fold_1.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected_footprints_score.txt",
                    "footprint_plot.chrombpnet_nobias.bias_motif.summary.fold_1.ENCSR868FGK.png"
                ]
            ],
            "logs.performance_metrics.fold_1.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/preds.log.e",
                        "preds.log.e"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/test/preds.log.o",
                        "preds.log.o"
                    ]
                ]
            },
            "footprint_plot.bias_motif.fold_1.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected.tn5_1.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_1.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias.tn5_1.footprint.png",
                        "footprint.bias_scaled.bias_motif_1.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected.tn5_2.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_2.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias.tn5_2.footprint.png",
                        "footprint.bias_scaled.bias_motif_2.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected.tn5_3.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_3.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias.tn5_3.footprint.png",
                        "footprint.bias_scaled.bias_motif_3.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected.tn5_4.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_4.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias.tn5_4.footprint.png",
                        "footprint.bias_scaled.bias_motif_4.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected.tn5_5.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_5.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias.tn5_5.footprint.png",
                        "footprint.bias_scaled.bias_motif_5.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias_footprints_score.txt",
                        "footprint_plot.bias_scaled.bias_motif.summary.fold_1.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/bias_footprints.h5",
                        "footprint.bias_scaled.bias_motif.all.fold_1.ENCSR868FGK.h5"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_1_data_type_ATAC_PE/footprints/corrected_footprints.h5",
                        "footprint.chrombpnet_nobias.bias_motif.all.fold_1.ENCSR868FGK.h5"
                    ]
                ]
            }
        },
        "fold_2": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_predictions.h5",
                    "predictions.chrombpnet.testset.fold_2.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_wo_bias_predictions.h5",
                    "predictions.chrombpnet_nobias.testset.fold_2.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.peaks.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.peaks.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.all.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.all.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.peaks.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.peaks.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.all.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.all.testset.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_metrics.json",
                    "performance_metrics.chrombpnet.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/chrombpnet_wo_bias_metrics.json",
                    "performance_metrics.chrombpnet_nobias.fold_2.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected_footprints_score.txt",
                    "footprint_plot.chrombpnet_nobias.bias_motif.summary.fold_2.ENCSR868FGK.png"
                ]
            ],
            "logs.performance_metrics.fold_2.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/preds.log.e",
                        "preds.log.e"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/test/preds.log.o",
                        "preds.log.o"
                    ]
                ]
            },
            "footprint_plot.bias_motif.fold_2.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected.tn5_1.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_1.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias.tn5_1.footprint.png",
                        "footprint.bias_scaled.bias_motif_1.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected.tn5_2.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_2.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias.tn5_2.footprint.png",
                        "footprint.bias_scaled.bias_motif_2.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected.tn5_3.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_3.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias.tn5_3.footprint.png",
                        "footprint.bias_scaled.bias_motif_3.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected.tn5_4.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_4.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias.tn5_4.footprint.png",
                        "footprint.bias_scaled.bias_motif_4.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected.tn5_5.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_5.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias.tn5_5.footprint.png",
                        "footprint.bias_scaled.bias_motif_5.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias_footprints_score.txt",
                        "footprint_plot.bias_scaled.bias_motif.summary.fold_2.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/bias_footprints.h5",
                        "footprint.bias_scaled.bias_motif.all.fold_2.ENCSR868FGK.h5"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_2_data_type_ATAC_PE/footprints/corrected_footprints.h5",
                        "footprint.chrombpnet_nobias.bias_motif.all.fold_2.ENCSR868FGK.h5"
                    ]
                ]
            }
        },
        "fold_3": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_predictions.h5",
                    "predictions.chrombpnet.testset.fold_3.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_wo_bias_predictions.h5",
                    "predictions.chrombpnet_nobias.testset.fold_3.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.peaks.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.peaks.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.all.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.all.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.peaks.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.peaks.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.all.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.all.testset.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_metrics.json",
                    "performance_metrics.chrombpnet.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/chrombpnet_wo_bias_metrics.json",
                    "performance_metrics.chrombpnet_nobias.fold_3.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected_footprints_score.txt",
                    "footprint_plot.chrombpnet_nobias.bias_motif.summary.fold_3.ENCSR868FGK.png"
                ]
            ],
            "logs.performance_metrics.fold_3.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/preds.log.e",
                        "preds.log.e"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/test/preds.log.o",
                        "preds.log.o"
                    ]
                ]
            },
            "footprint_plot.bias_motif.fold_3.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected.tn5_1.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_1.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias.tn5_1.footprint.png",
                        "footprint.bias_scaled.bias_motif_1.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected.tn5_2.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_2.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias.tn5_2.footprint.png",
                        "footprint.bias_scaled.bias_motif_2.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected.tn5_3.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_3.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias.tn5_3.footprint.png",
                        "footprint.bias_scaled.bias_motif_3.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected.tn5_4.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_4.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias.tn5_4.footprint.png",
                        "footprint.bias_scaled.bias_motif_4.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected.tn5_5.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_5.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias.tn5_5.footprint.png",
                        "footprint.bias_scaled.bias_motif_5.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias_footprints_score.txt",
                        "footprint_plot.bias_scaled.bias_motif.summary.fold_3.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/bias_footprints.h5",
                        "footprint.bias_scaled.bias_motif.all.fold_3.ENCSR868FGK.h5"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_3_data_type_ATAC_PE/footprints/corrected_footprints.h5",
                        "footprint.chrombpnet_nobias.bias_motif.all.fold_3.ENCSR868FGK.h5"
                    ]
                ]
            }
        },
        "fold_4": {
            "file.paths": [
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_predictions.h5",
                    "predictions.chrombpnet.testset.fold_4.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_wo_bias_predictions.h5",
                    "predictions.chrombpnet_nobias.testset.fold_4.ENCSR868FGK.h5"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.peaks.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.peaks.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet.all.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.png",
                    "obs_pred_scatter_plot.counts.chrombpnet_nobias.all.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.peaks.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_wo_bias_only_peaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.peaks.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet.all.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_wo_bias_peaks_and_nonpeaks.jsd.png",
                    "jsd_histogram_plot.profiles.chrombpnet_nobias.all.testset.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_metrics.json",
                    "performance_metrics.chrombpnet.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/chrombpnet_wo_bias_metrics.json",
                    "performance_metrics.chrombpnet_nobias.fold_4.ENCSR868FGK.png"
                ],
                [
                    "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected_footprints_score.txt",
                    "footprint_plot.chrombpnet_nobias.bias_motif.summary.fold_4.ENCSR868FGK.png"
                ]
            ],
            "logs.performance_metrics.fold_4.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/preds.log.e",
                        "preds.log.e"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/test/preds.log.o",
                        "preds.log.o"
                    ]
                ]
            },
            "footprint_plot.bias_motif.fold_4.ENCSR868FGK": {
                "file.paths": [
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected.tn5_1.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_1.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias.tn5_1.footprint.png",
                        "footprint.bias_scaled.bias_motif_1.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected.tn5_2.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_2.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias.tn5_2.footprint.png",
                        "footprint.bias_scaled.bias_motif_2.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected.tn5_3.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_3.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias.tn5_3.footprint.png",
                        "footprint.bias_scaled.bias_motif_3.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected.tn5_4.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_4.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias.tn5_4.footprint.png",
                        "footprint.bias_scaled.bias_motif_4.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected.tn5_5.footprint.png",
                        "footprint.chrombpnet_nobias.bias_motif_5.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias.tn5_5.footprint.png",
                        "footprint.bias_scaled.bias_motif_5.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias_footprints_score.txt",
                        "footprint_plot.bias_scaled.bias_motif.summary.fold_4.ENCSR868FGK.png"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/bias_footprints.h5",
                        "footprint.bias_scaled.bias_motif.all.fold_4.ENCSR868FGK.h5"
                    ],
                    [
                        "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/K562/K562_07.07.2022_bias_128_4_2356_0.5_fold_4_data_type_ATAC_PE/footprints/corrected_footprints.h5",
                        "footprint.chrombpnet_nobias.bias_motif.all.fold_4.ENCSR868FGK.h5"
                    ]
                ]
            }
        }
    },
    "bpnet quality metrics json": "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/ATAC/ENCSR868FGK/median_chrombpnet_performance.json"
}