import argparse
import pickle
import operator
import pysam
import numpy as np 
from scipy.special import softmax 
import tensorflow
import pybedtools
import pyBigWig
from tensorflow.compat.v1.keras.backend import get_session
tensorflow.compat.v1.disable_v2_behavior()
import math
import kerasAC 
from scipy.special import softmax,expit
from kerasAC.interpret.deepshap import * 
from kerasAC.interpret.profile_shap import * 
from kerasAC.vis import * 
from kerasAC.helpers.transform_bpnet_io import * 
from kerasAC.util import * 
import pandas as pd
from statsmodels.distributions.empirical_distribution import ECDF
import pyBigWig
import pdb 
#load the model! 
from keras.models import load_model
from keras.utils.generic_utils import get_custom_objects
from kerasAC.metrics import * 
from kerasAC.custom_losses import *

def parse_args():
    parser=argparse.ArgumentParser()
    parser.add_argument("--model_path")
    parser.add_argument("--background_pickle",help="This is a dictionary of the form (chrom, start, end, summit)->{signal_entropy; count_signal; ref_seq in ACGT; shuffled_seq in ACTG; count_preds; probability_preds }. This is generated by the script get_null_set_for_tf_background.py")
    parser.add_argument("--pwm_consensus_pickle",help="This is a dictionary of the form motif_name --> [list of kmer in ACTG]. This is generated by the script get_top_n_consensus_for_pwm.py")
    parser.add_argument("--motif_list_to_score",nargs="+",default=None,help="if None, score all the motifs in the file") 
    parser.add_argument("--out_prefix")
    return parser.parse_args()

def load_model_wrapper(model_path):
    custom_objects={"recall":recall,
                    "sensitivity":recall,
                    "specificity":specificity,
                    "fpr":fpr,
                    "fnr":fnr,
                    "precision":precision,
                    "f1":f1,
                    "ambig_binary_crossentropy":ambig_binary_crossentropy,
                    "ambig_mean_absolute_error":ambig_mean_absolute_error,
                    "ambig_mean_squared_error":ambig_mean_squared_error,
                    "MultichannelMultinomialNLL":MultichannelMultinomialNLL}
    get_custom_objects().update(custom_objects)
    model=load_model(model_path)
    return model

def get_deepshap(prof_explainer,count_explainer,seq_onehot):
    #dim will be (1,2114,4)
    hyp_profile_explanations=prof_explainer.shap_values(seq_onehot)
    hyp_count_explanations=count_explainer.shap_values(seq_onehot)[0]
    
    profile_explanations=np.squeeze(hyp_profile_explanations*seq_onehot).sum(axis=-1)
    count_explanations=np.squeeze(hyp_count_explanations*seq_onehot).sum(axis=-1)
    
    return np.squeeze(hyp_profile_explanations), np.squeeze(hyp_count_explanations), profile_explanations, count_explanations 


def get_preds(model,seq_onehot):
    preds=model.predict(seq_onehot)
    prof=preds[0] #logits
    probs=np.squeeze(softmax(prof,axis=1)) #probabilities 
    count=np.squeeze(preds[1])   #count (1 val)
    count_track=probs*np.exp(count)  #count track 
    return prof,count,probs,count_track

def main():
    args=parse_args()
    model=load_model_wrapper(args.model_path)
    print("loaded model")
    #create the explainers 
    model_wrapper=(model.input, model.outputs[1])
    count_explainer=shap.DeepExplainer(model_wrapper,
                                   data=create_background_atac,
                                   combine_mult_and_diffref=combine_mult_and_diffref_1d)
    print("created shap explainers") 
    
    prof_output = model.output[0]                                                                                                      
    logits = prof_output - tf.reduce_mean(prof_output, axis=1, keepdims=True)
    logits_stopgrad=tf.stop_gradient(logits)
    probs=tf.nn.softmax(logits_stopgrad,axis=1)
    logits_weighted=logits*probs 
    prof_sum=tf.reduce_sum(logits_weighted,axis=(1,2))
    prof_explainer=shap.DeepExplainer(model=(model.input,prof_sum),
                                  data=create_background_atac,
                                  combine_mult_and_diffref=combine_mult_and_diffref_1d)
    
    #load the pwm sequence regions
    with open(args.pwm_consensus_pickle,'rb') as f:
        pwm_sequences=pickle.load(f)
        
    if args.motif_list_to_score is None:
        pwm_list_to_score=list(pwm_sequences.keys())
    else:
        pwm_list_to_score=args.motif_list_to_score 
        
    #load the background regions
    with open(args.background_pickle,'rb') as f:
        background_regions=pickle.load(f)

    outputs={}
    
    #iterate through the background x sequence combinations, getting predictions and deepSHAP scores for each one 
    for motif_name in pwm_list_to_score:
        outputs[motif_name]={}
        candidate_sequences_actg=pwm_sequences[motif_name]
        candidate_sequences=one_hot_encode(candidate_sequences_actg)
        for candidate_sequence_index in range(candidate_sequences.shape[0]):
            cur_candidate_sequence=candidate_sequences[candidate_sequence_index,:,:]
            outputs[motif_name][candidate_sequences_actg[candidate_sequence_index]]={} 
            for background_region_coordinates in background_regions:
                shuffled_seq=one_hot_encode([background_regions[background_region_coordinates]['shuffled_seq']])
                #insert the kmer into the center of the background region
                background_center=shuffled_seq.shape[1]//2
                kmer_length_half = candidate_sequences.shape[1]//2
                kmer_start_pos=background_center-kmer_length_half
                to_score=shuffled_seq
                to_score[:,kmer_start_pos:kmer_start_pos+candidate_sequences.shape[1],:]=cur_candidate_sequence
                #get the prediction and interpretations
                
                #profile head out, count head out, probability predicted track, count predicted track 
                predicted_profile_logit_head,predicted_count_head,predicted_prob_track,predicted_count_track=get_preds(model,to_score)
                #subtract out the background
                background_count_signal=background_regions[background_region_coordinates]['count_preds']
                predicted_count_track_minus_background=predicted_count_track - background_count_signal
                #get deepSHAP scores  
                hyp_profile_explanations_shap, hyp_count_explanations_shap,profile_explanations_shap, count_explanations_shap=get_deepshap(prof_explainer, count_explainer, to_score)
                outputs[motif_name][candidate_sequences_actg[candidate_sequence_index]][background_region_coordinates]={'predicted_count_track': predicted_count_track,
                                                                                        'predicted_count_track_minus_background':predicted_count_track_minus_background,
                                                                                        'hyp_profile_explanations_shap':hyp_profile_explanations_shap,
                                                                                        'hyp_count_exlanations_shap':hyp_count_explanations_shap,
                                                                                        'profile_explanations_shap':profile_explanations_shap,
                                                                                        'count_explanations_shap':count_explanations_shap}
    with open(args.out_prefix+'motif.scores.pkl','wb') as handle:
            pickle.dump(outputs,handle,protocol=pickle.HIGHEST_PROTOCOL)

if __name__=="__main__":
    main()
    
